<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Version>1.0.0</Version>
	<PackageId>Darkwolf.Shared.Persistence</PackageId>
	<Authors>Vicky</Authors>
	<Company>Darkwolf</Company>
	<Description>A shared library for Darkwolf projects</Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.21" />
  </ItemGroup>

</Project>
