<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Version>1.2.0</Version>
	<PackageId>Darkwolf.Shared.Extensions</PackageId>
	<Authors>Vicky</Authors>
	<Company>Darkwolf</Company>
	<Description>A shared library for Darkwolf projects</Description>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Darkwolf.Shared.Authentication" Version="1.1.0" />
    <PackageReference Include="Darkwolf.Shared.Common" Version="1.0.0" />
    <PackageReference Include="Darkwolf.Shared.Infrastructure" Version="1.0.0" />
    <PackageReference Include="Darkwolf.Shared.Logging" Version="1.0.0" />
    <PackageReference Include="Darkwolf.Shared.Middleware" Version="1.0.0" />
    <PackageReference Include="Darkwolf.Shared.Persistence" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
